source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 6.0.3', '>= 6.0.3', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'slim'
gem 'rest-client'
gem 'sinatra-cache'
gem 'sysrandom'
gem 'rack-flash3'
gem 'geocoder'
gem 'will_paginate'
gem 'mail'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
